// src/utils/generateReport.js
import appIcon from "../assets/app_icon1.png";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { adminFetch, getImageUrl } from "../api/adminClient";

// ============================================================
// HELPERS
// ============================================================

const formatDate = (dt) => {
  if (!dt) return "—";
  const d = new Date(dt);
  return d.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
};

const getAvatarSrc = (url, name = "") => {
  if (url && typeof url === "string" && url.trim() !== "") return url;
  const initials = (name || "S T")
    .split(" ")
    .filter(Boolean)
    .map((n) => n[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(
    initials,
  )}&background=E5E7EB&color=374151&bold=true&size=128`;
};

// ============================================================
// FETCH HELPERS
// ============================================================

const safeFetch = async (url, options = {}) => {
  try {
    const res = await adminFetch(url, options);
    if (!res.ok) return null;
    return await res.json();
  } catch (err) {
    console.error(`Failed to fetch ${url}:`, err);
    return null;
  }
};

const fetchDashboard = () => safeFetch("/api/admin/dashboard");

const fetchTutors = () =>
  safeFetch("/api/admin/tutors/filter", {
    method: "POST",
    body: JSON.stringify({}), // no filters = all tutors
  });

const fetchStudents = () =>
  safeFetch("/api/admin/students/filter", {
    method: "POST",
    body: JSON.stringify({}),
  });

const fetchCourses = () =>
  safeFetch("/api/admin/courses/filter", {
    method: "POST",
    body: JSON.stringify({}),
  });

const fetchReviews = () =>
  safeFetch("/api/admin/reviews/filter", {
    method: "POST",
    body: JSON.stringify({}),
  });

const fetchVerifications = async () => {
  const [pending, approved, rejected] = await Promise.all([
    safeFetch("/api/admin/verifications?status=PENDING"),
    safeFetch("/api/admin/verifications?status=APPROVED"),
    safeFetch("/api/admin/verifications?status=REJECTED"),
  ]);
  return {
    pending: Array.isArray(pending) ? pending : [],
    approved: Array.isArray(approved) ? approved : [],
    rejected: Array.isArray(rejected) ? rejected : [],
  };
};

// ============================================================
// HELPER — Convert an image URL/import to a base64 data URL
// (needed because jsPDF's addImage wants a data URL)
// ============================================================
const toBase64 = (src) =>
  new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      const ctx = canvas.getContext("2d");
      ctx.drawImage(img, 0, 0);
      resolve(canvas.toDataURL("image/png"));
    };
    img.onerror = reject;
    img.src = src;
  });

// ============================================================
// PDF BUILDING BLOCKS
// ============================================================

const addCoverPage = (doc, adminName, iconDataUrl = null) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // ---------- Header black band ----------
  doc.setFillColor(0, 0, 0);
  doc.rect(0, 0, pageWidth, 90, "F");

  // ---------- Icon (top-left of the black band) ----------
  let textLeft = 20; // where the "TUTR" text begins
  if (iconDataUrl) {
    try {
      const iconSize = 20;          // 20mm square
      const iconX = 20;             // left margin
      const iconY = 32;             // vertically centred in the 90mm band
      doc.addImage(iconDataUrl, "PNG", iconX, iconY, iconSize, iconSize);

      // Shift text right so it doesn't overlap the icon
      textLeft = iconX + iconSize + 6;
    } catch (e) {
      console.warn("Failed to embed icon in PDF:", e);
      textLeft = 20; // fall back
    }
  }

  // ---------- Title ----------
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(32);
  doc.setFont("helvetica", "bold");
  doc.text("TUTR", textLeft, 45);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Admin Console — System Report", textLeft, 58);

  // Reset text color
  doc.setTextColor(0, 0, 0);

  // ---------- Body ----------
  let y = 130;
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Executive Summary Report", 20, y);
  y += 12;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(
    `Generated on: ${new Date().toLocaleString("en-US", {
      dateStyle: "long",
      timeStyle: "short",
    })}`,
    20,
    y,
  );
  y += 8;

  doc.text(`Generated by: ${adminName}`, 20, y);
  y += 25;

  // Divider
  doc.setDrawColor(230, 230, 230);
  doc.line(20, y, pageWidth - 20, y);
  y += 15;

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Contents:", 20, y);
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const contents = [
    "1.  Executive Dashboard Statistics",
    "2.  Tutor Breakdown & Directory",
    "3.  Student Breakdown & Directory",
    "4.  Course Catalog & Distribution",
    "5.  Reviews & Ratings Overview",
    "6.  Verification Requests Summary",
  ];
  contents.forEach((line) => {
    doc.text(line, 25, y);
    y += 7;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "TUTR Admin Console  •  Confidential  •  Page 1",
    pageWidth / 2,
    pageHeight - 15,
    { align: "center" },
  );
};

const addSectionHeader = (doc, title, y) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;

  // Check if we need a new page
  if (y > doc.internal.pageSize.getHeight() - 40) {
    doc.addPage();
    y = 20;
  }

  doc.setFillColor(0, 0, 0);
  doc.rect(margin, y, pageWidth - margin * 2, 12, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(title, margin + 5, y + 8);

  doc.setTextColor(0, 0, 0);
  return y + 18;
};

// ============================================================
// MAIN EXPORT — Build the full report
// ============================================================

export const generateFullAppPDF = async (
  navigate,
  setProgressText,
  adminName = "Admin",
) => {
  setProgressText?.("Fetching dashboard data...");
  const dashboard = await fetchDashboard();

  setProgressText?.("Fetching tutors...");
  const tutorsRaw = await fetchTutors();
  const tutors = Array.isArray(tutorsRaw) ? tutorsRaw : [];

  setProgressText?.("Fetching students...");
  const studentsRaw = await fetchStudents();
  const students = Array.isArray(studentsRaw) ? studentsRaw : [];

  setProgressText?.("Fetching courses...");
  const coursesRaw = await fetchCourses();
  const courses = Array.isArray(coursesRaw) ? coursesRaw : [];

  setProgressText?.("Fetching reviews...");
  const reviewsRaw = await fetchReviews();
  const reviews = Array.isArray(reviewsRaw) ? reviewsRaw : [];

  setProgressText?.("Fetching verifications...");
  const verifications = await fetchVerifications();

  setProgressText?.("Preparing assets...");

// Convert the icon (imported as a module URL) to a base64 data URL
let iconDataUrl = null;
try {
  iconDataUrl = await toBase64(appIcon);
} catch (e) {
  console.warn("Icon conversion failed, PDF will render without logo:", e);
}

  setProgressText?.("Building PDF...");

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;

  // ----------------------------------------------------------
  // PAGE 1 — COVER
  // ----------------------------------------------------------
  addCoverPage(doc, adminName, iconDataUrl);

  // ----------------------------------------------------------
  // PAGE 2 — EXECUTIVE STATISTICS
  // ----------------------------------------------------------
  doc.addPage();
  let y = 20;

  y = addSectionHeader(doc, "1.  Executive Dashboard Statistics", y);

  const stats = dashboard?.stats || {};
  const statsRows = [
    ["Total Users", String(stats.totalUsers ?? 0)],
    ["Total Tutors", String(stats.totalTutors ?? 0)],
    ["Total Students", String(stats.totalStudents ?? 0)],
    ["Pending Verifications", String(stats.pendingVerifications ?? 0)],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value"]],
    body: statsRows,
    theme: "grid",
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    columnStyles: {
      0: { cellWidth: 80, fontStyle: "bold" },
      1: { cellWidth: "auto" },
    },
    margin: { left: margin, right: margin },
  });
  y = doc.lastAutoTable.finalY + 12;

  // ----------------------------------------------------------
  // TUTORS SECTION
  // ----------------------------------------------------------
  y = addSectionHeader(doc, "2.  Tutor Breakdown & Directory", y);

  // Tutor status distribution
  const tutorByStatus = {
    Active: tutors.filter((t) => (t.status || "").toUpperCase() === "ACTIVE")
      .length,
    Inactive: tutors.filter((t) => (t.status || "").toUpperCase() === "INACTIVE")
      .length,
    Suspended: tutors.filter(
      (t) => (t.status || "").toUpperCase() === "SUSPENDED",
    ).length,
    Pending: tutors.filter((t) => (t.status || "").toUpperCase() === "PENDING")
      .length,
    Total: tutors.length,
  };

  autoTable(doc, {
    startY: y,
    head: [["Status", "Count"]],
    body: Object.entries(tutorByStatus).map(([k, v]) => [k, String(v)]),
    theme: "grid",
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    columnStyles: { 0: { cellWidth: 80, fontStyle: "bold" } },
    margin: { left: margin, right: margin },
  });
  y = doc.lastAutoTable.finalY + 10;

  // Tutor table
  if (tutors.length > 0) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Tutor Directory", margin, y);
    y += 5;

    autoTable(doc, {
      startY: y,
      head: [["ID", "Name", "Email", "Role", "Status", "Rating"]],
      body: tutors.map((t) => [
        `TTR-${t.id ?? "—"}`,
        t.name || "—",
        t.email || "—",
        t.role || "TUTOR",
        t.status || "—",
        t.rating != null ? Number(t.rating).toFixed(1) : "—",
      ]),
      theme: "striped",
      headStyles: { fillColor: [24, 24, 27], textColor: [255, 255, 255] },
      styles: { fontSize: 8, cellPadding: 2 },
      margin: { left: margin, right: margin },
    });
    y = doc.lastAutoTable.finalY + 12;
  }

  // ----------------------------------------------------------
  // STUDENTS SECTION
  // ----------------------------------------------------------
  y = addSectionHeader(doc, "3.  Student Breakdown & Directory", y);

  const studentByStatus = {
    Active: students.filter((s) => (s.status || "").toUpperCase() === "ACTIVE")
      .length,
    Suspended: students.filter(
      (s) => (s.status || "").toUpperCase() === "SUSPENDED",
    ).length,
    Total: students.length,
  };

  autoTable(doc, {
    startY: y,
    head: [["Status", "Count"]],
    body: Object.entries(studentByStatus).map(([k, v]) => [k, String(v)]),
    theme: "grid",
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    columnStyles: { 0: { cellWidth: 80, fontStyle: "bold" } },
    margin: { left: margin, right: margin },
  });
  y = doc.lastAutoTable.finalY + 10;

  if (students.length > 0) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Student Directory", margin, y);
    y += 5;

    autoTable(doc, {
      startY: y,
      head: [["ID", "Name", "Email", "Status", "Courses"]],
      body: students.map((s) => [
        `STU-${s.id ?? "—"}`,
        s.name || "—",
        s.email || "—",
        s.status || "—",
        String(s.coursesEnrolled ?? 0),
      ]),
      theme: "striped",
      headStyles: { fillColor: [24, 24, 27], textColor: [255, 255, 255] },
      styles: { fontSize: 8, cellPadding: 2 },
      margin: { left: margin, right: margin },
    });
    y = doc.lastAutoTable.finalY + 12;
  }

  // ----------------------------------------------------------
  // COURSES SECTION
  // ----------------------------------------------------------
  y = addSectionHeader(doc, "4.  Course Catalog & Distribution", y);

  // Category distribution
  const courseByCategory = {};
  courses.forEach((c) => {
    const cat = c.category || "Uncategorized";
    courseByCategory[cat] = (courseByCategory[cat] || 0) + 1;
  });

  autoTable(doc, {
    startY: y,
    head: [["Category", "Count"]],
    body: Object.entries(courseByCategory).map(([k, v]) => [k, String(v)]),
    theme: "grid",
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    columnStyles: { 0: { cellWidth: 80, fontStyle: "bold" } },
    margin: { left: margin, right: margin },
  });
  y = doc.lastAutoTable.finalY + 10;

  if (courses.length > 0) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Course Directory", margin, y);
    y += 5;

    autoTable(doc, {
      startY: y,
      head: [
        ["ID", "Title", "Category", "Instructor", "Status", "Mode", "Enrolled"],
      ],
      body: courses.map((c) => [
        c.id ?? "—",
        c.title || "—",
        c.category || "—",
        c.instructorName || c.instructor || "—",
        c.status || "—",
        c.mode || "—",
        String(c.enrolledStudents ?? 0),
      ]),
      theme: "striped",
      headStyles: { fillColor: [24, 24, 27], textColor: [255, 255, 255] },
      styles: { fontSize: 7, cellPadding: 2 },
      margin: { left: margin, right: margin },
    });
    y = doc.lastAutoTable.finalY + 12;
  }

  // ----------------------------------------------------------
  // REVIEWS SECTION
  // ----------------------------------------------------------
  y = addSectionHeader(doc, "5.  Reviews & Ratings Overview", y);

  if (reviews.length > 0) {
    const totalRatings = reviews.reduce((s, r) => s + (r.rating || 0), 0);
    const avg = totalRatings / reviews.length;
    const distribution = { 5: 0, 4: 0, 3: 0, 2: 0, 1: 0 };
    reviews.forEach((r) => {
      if (distribution[r.rating] != null) distribution[r.rating]++;
    });

    autoTable(doc, {
      startY: y,
      head: [["Metric", "Value"]],
      body: [
        ["Total Reviews", String(reviews.length)],
        ["Average Rating", avg.toFixed(2)],
        ["5 Stars", String(distribution[5])],
        ["4 Stars", String(distribution[4])],
        ["3 Stars", String(distribution[3])],
        ["2 Stars", String(distribution[2])],
        ["1 Star", String(distribution[1])],
      ],
      theme: "grid",
      headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
      columnStyles: { 0: { cellWidth: 80, fontStyle: "bold" } },
      margin: { left: margin, right: margin },
    });
    y = doc.lastAutoTable.finalY + 12;
  } else {
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.setFont("helvetica", "italic");
    doc.text("No reviews available.", margin, y);
    doc.setTextColor(0, 0, 0);
    y += 12;
  }

  // ----------------------------------------------------------
  // VERIFICATIONS SECTION
  // ----------------------------------------------------------
  y = addSectionHeader(doc, "6.  Verification Requests Summary", y);

  autoTable(doc, {
    startY: y,
    head: [["Status", "Count"]],
    body: [
      ["Pending", String(verifications.pending.length)],
      ["Approved", String(verifications.approved.length)],
      ["Rejected", String(verifications.rejected.length)],
      ["Total", String(
        verifications.pending.length +
          verifications.approved.length +
          verifications.rejected.length,
      )],
    ],
    theme: "grid",
    headStyles: { fillColor: [0, 0, 0], textColor: [255, 255, 255] },
    columnStyles: { 0: { cellWidth: 80, fontStyle: "bold" } },
    margin: { left: margin, right: margin },
  });

  // ----------------------------------------------------------
  // FOOTER ON ALL PAGES
  // ----------------------------------------------------------
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 2; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `TUTR Admin Console  •  Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: "center" },
    );
  }

  // ----------------------------------------------------------
  // SAVE
  // ----------------------------------------------------------
  const today = new Date().toISOString().slice(0, 10);
  doc.save(`TUTR_Admin_Report_${today}.pdf`);
};